#!/bin/bash
set -e

groupmod -g 499 cgred
usermod -u 803 unbound
groupmod -g 803 unbound
usermod -u 805 saslauth
groupmod -g 805 saslauth
groupmod -g 998 polkitd
service memcached stop
usermod -u 804 memcached
groupmod -g 804 memcached
service memcached start
