#!/bin/bash

TARGET="$1"

. /var/lib/edeploy/conf

if [ -z "$TARGET" ]; then
    echo "Usage: $0 <target version>" 2>&1
    exit 1
fi

set -e
set -x

mkdir -p /var/lib/edeploy

rsync -a ${SERV}::metadata/${VERS}/${ROLE}/${TARGET}/ /var/lib/edeploy/${TARGET}/

cd /var/lib/edeploy/${TARGET}/

if [ -x pre ]; then
    ./pre
fi

rsync -av --delete --exclude-from=exclude ${SERV}::install/${TARGET}/${ROLE}/ / > /var/lib/edeploy/rsync_${VERS}_${TARGET}.out

set +e

if [ -x post ]; then
    ./post
    RET=$?
fi

echo -e "\nVersion ${TARGET}\n" > /etc/motd
echo -e "VERS=${TARGET}\nROLE=${ROLE}\nSERV=${SERV}\n" > /var/lib/edeploy/conf

echo "Upgraded to $TARGET"

if [ $RET = 100 ]; then
    echo "Reboot requested by the upgrade process..."
    sync
    sleep 2
    reboot
fi
