#!/bin/bash

src="$1"
dir="$2"
version="$3"

ROLE=mysql

ORIG=$(cd $(dirname $0); pwd)

. ${ORIG}/functions

chroot ${dir} debconf-set-selections <<< 'mysql-server-5.1 mysql-server/root_password password your_password'
chroot ${dir} debconf-set-selections <<< 'mysql-server-5.1 mysql-server/root_password_again password your_password'

chroot ${dir} apt-get update
chroot ${dir} apt-get install -y --force-yes puppet-common openssh-server mysql-server
chroot ${dir} apt-get clean
