#!/bin/bash

BASE="$0"
ROLE="$1"
FROM="$2"
TO="$3"
DEST="$4"

ORIG=$(cd $(dirname $0); pwd)
FDIR=${DEST}/install/${FROM}/${ROLE}
TDIR=${DEST}/install/${TO}/${ROLE}

if [ $# != 4 ]; then
    echo "Usage: $0 <role> <base version> <new version> <top dir>" 1>&2
    exit 1
fi

if [ ! -d "$FDIR" ]; then
    echo "Source directory $FDIR deson't exist" 1>&2
    exit 1
fi

export DEBIAN_FRONTEND=noninteractive

set -e
set -x

if [ ! -d ${TDIR} ]; then
    mkdir -p ${TDIR}

    rsync -av --delete ${FDIR}/ ${TDIR}/
fi

cleanup() {
    umount ${TDIR}/dev
}

trap cleanup 0

mount -obind /dev ${TDIR}/dev
chroot ${TDIR} apt-get update
cp -p ${ORIG}/edeploy ${TDIR}/usr/sbin/
echo -e "VERS=${TO}\nROLE=${ROLE}\n" > ${TDIR}/var/lib/edeploy/conf

mkdir -p ${TDIR}/etc/default/grub.d
echo 'exit 0' > ${TDIR}/etc/default/grub.d/edeploy.cfg

script="$BASE".d/${ROLE}_${FROM}_${TO}.upgrade

if [ -x "$script" ]; then
    "$script" $ROLE $FROM $TO $TDIR
fi

rm -f ${TDIR}/etc/default/grub.d/edeploy.cfg

chroot ${TDIR} apt-get clean
chroot ${TDIR} dpkg -l > ${TDIR}/../${ROLE}.dpkg
