#!/bin/sh
set -e

# ids.tables moved to /etc
rm -f /root/ids.tables

# Horizon
mkdir -p /var/lib/openstack-dashboard/static/js
mkdir -p /var/lib/openstack-dashboard/static/css
mkdir -p /var/lib/openstack-dashboard/secret-key
chown www-data:www-data /var/lib/openstack-dashboard/static
chown www-data:www-data /var/lib/openstack-dashboard/static/css
chown www-data:www-data /var/lib/openstack-dashboard/static/js
chown www-data:www-data /var/lib/openstack-dashboard/secret-key
# Compress the JS and CSS with python-compressor and python-lesscpy
/usr/share/openstack-dashboard/manage.py compress --force
rm /var/lib/openstack-dashboard/secret-key/.secret_key_store
chown -R www-data /var/lib/openstack-dashboard/secret-key
pycompile -p openstack-dashboard /usr/share/openstack-dashboard

groupadd -g 800 messagebus
useradd -u 800 -g messagebus -d /var/run/dbus -s /bin/false messagebus

export DEBIAN_FRONTEND=noninteractive
/var/lib/dpkg/info/linux-image-3.16-0.bpo.2-amd64.postinst configure

exit 0
