#!/bin/sh
set -e

# ids.tables moved to /etc
rm -f /root/ids.tables

# Horizon
pycompile -p python-django-horizon
pycompile -p openstack-dashboard /usr/share/openstack-dashboard

groupadd -g 800 messagebus
useradd -u 800 -g messagebus -d /var/run/dbus -s /bin/false messagebus

exit 0
