#!/bin/sh
set -e

# ids.tables moved to /etc
rm -rf /root/ids.tables

groupadd -g 800 messagebus
useradd -u 800 -g messagebus -d /var/run/dbus -s /bin/false messagebus

export DEBIAN_FRONTEND=noninteractive
/var/lib/dpkg/info/linux-image-3.16-0.bpo.2-amd64.postinst configure

exit 0
