#!/bin/bash
set -e

groupmod -g 499 cgred
groupadd -g 26 postgres
groupadd -g 998 polkitd
groupadd -g 32 rpc
groupmod -g 800 redis
usermod -u 800 redis
groupmod -g 990 rabbitmq
usermod -u 991 rabbitmq
usermod -u 805 saslauth
groupmod -g 805 saslauth
chown -R redis:redis /var/log/redis
chown -R rabbitmq:rabbitmq /var/log/rabbitmq
useradd -u 26 -g postgres -d /var/lib/postgresql -s /bin/bash postgres
useradd -u 996 -g polkitd -d / -s /sbin/nologin polkitd
useradd -u 32 -g rpc -d /var/lib/rpcbind -s /sbin/nologin rpc
if [[ -x /etc/init.d/elasticsearch-fluentd ]] ; then
  /etc/init.d/elasticsearch-fluentd stop
fi
usermod -u 802 elasticsearch
groupmod -g 802 elasticsearch
if [[ -x /etc/init.d/elasticsearch-fluentd ]] ; then
  /etc/init.d/elasticsearch-fluentd start
fi
mkdir /var/log/postgresql
mkdir /var/run/postgresql
chown postgres:postgres /var/run/postgresql
