#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

/var/lib/dpkg/info/mysql-server-5.5.preinst upgrade 5.5.22-0ubuntu1

#/var/lib/dpkg/info/linux-image-3.2.0-40-virtual.preinst upgrade 3.2.0-23-virtual
