#
# Copyright (C) 2013 eNovance SAS <licensing@enovance.com>
#
# Author: Frederic Lepied <frederic.lepied@enovance.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import unittest

import detect

class TestDetect(unittest.TestCase):

    def test_detect_system(self):
        l = []
        detect.detect_system(l, XML)
        return self.assertEqual(
            l,
            [('system', 'product', 'serial', 'C02JR02WF57J'),
             ('system', 'product', 'name', 'MacBookAir5,2 (System SKU#)'),
             ('system', 'product', 'vendor', 'Apple Inc.'),
             ('system', 'product', 'version', '1.0'),
             ('system', 'memory', 'size', '8589934592'),
             ('network', 'vnet0', 'serial', 'fe:54:00:c1:1a:f7'),
             ('network', 'vnet0', 'size', '10000000'),
             ('network', 'vnet0', 'link', 'yes'),
             ('network', 'tap0', 'serial', 'e2:66:69:22:be:fb'),
             ('network', 'tap0', 'size', '10000000'),
             ('network', 'tap0', 'ipv4', '10.152.18.103'),
             ('network', 'tap0', 'link', 'yes'),
             ('network', 'wlan0', 'serial', '00:88:65:35:2b:50'),
             ('network', 'wlan0', 'ipv4', '192.168.12.13'),
             ('network', 'wlan0', 'link', 'yes'),
             ('system', 'cpu', 'number', '4')]
            )

XML = '''<?xml version="1.0" standalone="yes" ?>
<!-- generated by lshw-B.02.16 -->
<!-- GCC 4.7.1 -->
<!-- Linux 3.8.0-26-generic #38-Ubuntu SMP Mon Jun 17 21:43:33 UTC 2013 x86_64 -->
<!-- GNU libc 2 (glibc 2.17) -->
<list>
<node id="fred-macbookair" claimed="true" class="system" handle="DMI:001B">
 <description>Notebook</description>
 <product>MacBookAir5,2 (System SKU#)</product>
 <vendor>Apple Inc.</vendor>
 <version>1.0</version>
 <serial>C02JR02WF57J</serial>
 <width units="bits">64</width>
 <configuration>
  <setting id="boot" value="normal" />
  <setting id="chassis" value="notebook" />
  <setting id="family" value="MacBook Air" />
  <setting id="sku" value="System SKU#" />
  <setting id="uuid" value="32520E5E-DB6F-0A58-97C3-598FBCAACA5A" />
 </configuration>
 <capabilities>
  <capability id="smbios-2.4" >SMBIOS version 2.4</capability>
  <capability id="dmi-2.4" >DMI version 2.4</capability>
  <capability id="vsyscall32" >32-bit processes</capability>
 </capabilities>
  <node id="core" claimed="true" class="bus" handle="DMI:001C">
   <description>Motherboard</description>
   <product>Mac-2E6FAB96566FE58C</product>
   <vendor>Apple Inc.</vendor>
   <physid>0</physid>
   <version>MacBookAir5,2</version>
   <serial>C02245301ZFF25WAT</serial>
   <slot>Part Component</slot>
    <node id="cpu:0" claimed="true" class="processor" handle="DMI:0000">
     <description>CPU</description>
     <product>Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz</product>
     <vendor>Intel Corp.</vendor>
     <physid>0</physid>
     <businfo>cpu@0</businfo>
     <version>Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz</version>
     <slot>U2E1</slot>
     <size units="Hz">800000000</size>
     <capacity units="Hz">800000000</capacity>
     <width units="bits">64</width>
     <clock units="Hz">25000000</clock>
     <capabilities>
      <capability id="fpu" >mathematical co-processor</capability>
      <capability id="fpu_exception" >FPU exceptions reporting</capability>
      <capability id="wp" />
      <capability id="vme" >virtual mode extensions</capability>
      <capability id="de" >debugging extensions</capability>
      <capability id="pse" >page size extensions</capability>
      <capability id="tsc" >time stamp counter</capability>
      <capability id="msr" >model-specific registers</capability>
      <capability id="pae" >4GB+ memory addressing (Physical Address Extension)</capability>
      <capability id="mce" >machine check exceptions</capability>
      <capability id="cx8" >compare and exchange 8-byte</capability>
      <capability id="apic" >on-chip advanced programmable interrupt controller (APIC)</capability>
      <capability id="sep" >fast system calls</capability>
      <capability id="mtrr" >memory type range registers</capability>
      <capability id="pge" >page global enable</capability>
      <capability id="mca" >machine check architecture</capability>
      <capability id="cmov" >conditional move instruction</capability>
      <capability id="pat" >page attribute table</capability>
      <capability id="pse36" >36-bit page size extensions</capability>
      <capability id="clflush" />
      <capability id="dts" >debug trace and EMON store MSRs</capability>
      <capability id="acpi" >thermal control (ACPI)</capability>
      <capability id="mmx" >multimedia extensions (MMX)</capability>
      <capability id="fxsr" >fast floating point save/restore</capability>
      <capability id="sse" >streaming SIMD extensions (SSE)</capability>
      <capability id="sse2" >streaming SIMD extensions (SSE2)</capability>
      <capability id="ss" >self-snoop</capability>
      <capability id="ht" >HyperThreading</capability>
      <capability id="tm" >thermal interrupt and status</capability>
      <capability id="pbe" >pending break event</capability>
      <capability id="syscall" >fast system calls</capability>
      <capability id="nx" >no-execute bit (NX)</capability>
      <capability id="rdtscp" />
      <capability id="x86-64" >64bits extensions (x86-64)</capability>
      <capability id="constant_tsc" />
      <capability id="arch_perfmon" />
      <capability id="pebs" />
      <capability id="bts" />
      <capability id="rep_good" />
      <capability id="nopl" />
      <capability id="xtopology" />
      <capability id="nonstop_tsc" />
      <capability id="aperfmperf" />
      <capability id="eagerfpu" />
      <capability id="pni" />
      <capability id="pclmulqdq" />
      <capability id="dtes64" />
      <capability id="monitor" />
      <capability id="ds_cpl" />
      <capability id="vmx" />
      <capability id="smx" />
      <capability id="est" />
      <capability id="tm2" />
      <capability id="ssse3" />
      <capability id="cx16" />
      <capability id="xtpr" />
      <capability id="pdcm" />
      <capability id="pcid" />
      <capability id="sse4_1" />
      <capability id="sse4_2" />
      <capability id="x2apic" />
      <capability id="popcnt" />
      <capability id="tsc_deadline_timer" />
      <capability id="aes" />
      <capability id="xsave" />
      <capability id="avx" />
      <capability id="f16c" />
      <capability id="rdrand" />
      <capability id="lahf_lm" />
      <capability id="ida" />
      <capability id="arat" />
      <capability id="xsaveopt" />
      <capability id="pln" />
      <capability id="pts" />
      <capability id="dtherm" />
      <capability id="tpr_shadow" />
      <capability id="vnmi" />
      <capability id="flexpriority" />
      <capability id="ept" />
      <capability id="vpid" />
      <capability id="fsgsbase" />
      <capability id="smep" />
      <capability id="erms" />
      <capability id="cpufreq" >CPU Frequency scaling</capability>
     </capabilities>
      <node id="cache:0" claimed="true" class="memory" handle="DMI:0002">
       <description>L1 cache</description>
       <physid>2</physid>
       <slot>Unknown</slot>
       <size units="bytes">32768</size>
       <capacity units="bytes">32768</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
       </capabilities>
      </node>
      <node id="cache:1" claimed="true" class="memory" handle="DMI:0003">
       <description>L2 cache</description>
       <physid>3</physid>
       <slot>Unknown</slot>
       <size units="bytes">262144</size>
       <capacity units="bytes">262144</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
        <capability id="instruction" >Instruction cache</capability>
       </capabilities>
      </node>
      <node id="cache:2" claimed="true" class="memory" handle="DMI:0004">
       <description>L3 cache</description>
       <physid>4</physid>
       <slot>Unknown</slot>
       <size units="bytes">4096</size>
       <capacity units="bytes">4096</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
        <capability id="instruction" >Instruction cache</capability>
       </capabilities>
      </node>
    </node>
    <node id="cache:0" claimed="true" class="memory" handle="DMI:0001">
     <description>L1 cache</description>
     <physid>1</physid>
     <slot>Unknown</slot>
     <size units="bytes">32768</size>
     <capacity units="bytes">32768</capacity>
     <capabilities>
      <capability id="asynchronous" >Asynchronous</capability>
      <capability id="internal" >Internal</capability>
      <capability id="write-back" >Write-back</capability>
     </capabilities>
    </node>
    <node id="cpu:1" claimed="true" class="processor" handle="DMI:0005">
     <description>CPU</description>
     <vendor>Intel(R) Corporation</vendor>
     <physid>5</physid>
     <businfo>cpu@1</businfo>
     <version>Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz</version>
     <slot>U2E1</slot>
     <size units="Hz">800000000</size>
     <capacity units="Hz">800000000</capacity>
     <clock units="Hz">25000000</clock>
     <capabilities>
      <capability id="cpufreq" >CPU Frequency scaling</capability>
     </capabilities>
      <node id="cache:0" claimed="true" class="memory" handle="DMI:0007">
       <description>L1 cache</description>
       <physid>7</physid>
       <slot>Unknown</slot>
       <size units="bytes">32768</size>
       <capacity units="bytes">32768</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
       </capabilities>
      </node>
      <node id="cache:1" claimed="true" class="memory" handle="DMI:0008">
       <description>L2 cache</description>
       <physid>8</physid>
       <slot>Unknown</slot>
       <size units="bytes">262144</size>
       <capacity units="bytes">262144</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
        <capability id="instruction" >Instruction cache</capability>
       </capabilities>
      </node>
      <node id="cache:2" claimed="true" class="memory" handle="DMI:0009">
       <description>L3 cache</description>
       <physid>9</physid>
       <slot>Unknown</slot>
       <size units="bytes">4096</size>
       <capacity units="bytes">4096</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
        <capability id="instruction" >Instruction cache</capability>
       </capabilities>
      </node>
    </node>
    <node id="cache:1" claimed="true" class="memory" handle="DMI:0006">
     <description>L1 cache</description>
     <physid>6</physid>
     <slot>Unknown</slot>
     <size units="bytes">32768</size>
     <capacity units="bytes">32768</capacity>
     <capabilities>
      <capability id="asynchronous" >Asynchronous</capability>
      <capability id="internal" >Internal</capability>
      <capability id="write-back" >Write-back</capability>
     </capabilities>
    </node>
    <node id="cpu:2" claimed="true" class="processor" handle="DMI:000A">
     <description>CPU</description>
     <vendor>Intel(R) Corporation</vendor>
     <physid>a</physid>
     <businfo>cpu@2</businfo>
     <version>Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz</version>
     <slot>U2E1</slot>
     <size units="Hz">800000000</size>
     <capacity units="Hz">800000000</capacity>
     <clock units="Hz">25000000</clock>
     <capabilities>
      <capability id="cpufreq" >CPU Frequency scaling</capability>
     </capabilities>
      <node id="cache:0" claimed="true" class="memory" handle="DMI:000C">
       <description>L1 cache</description>
       <physid>c</physid>
       <slot>Unknown</slot>
       <size units="bytes">32768</size>
       <capacity units="bytes">32768</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
       </capabilities>
      </node>
      <node id="cache:1" claimed="true" class="memory" handle="DMI:000D">
       <description>L2 cache</description>
       <physid>d</physid>
       <slot>Unknown</slot>
       <size units="bytes">262144</size>
       <capacity units="bytes">262144</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
        <capability id="instruction" >Instruction cache</capability>
       </capabilities>
      </node>
      <node id="cache:2" claimed="true" class="memory" handle="DMI:000E">
       <description>L3 cache</description>
       <physid>e</physid>
       <slot>Unknown</slot>
       <size units="bytes">4096</size>
       <capacity units="bytes">4096</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
        <capability id="instruction" >Instruction cache</capability>
       </capabilities>
      </node>
    </node>
    <node id="cache:2" claimed="true" class="memory" handle="DMI:000B">
     <description>L1 cache</description>
     <physid>b</physid>
     <slot>Unknown</slot>
     <size units="bytes">32768</size>
     <capacity units="bytes">32768</capacity>
     <capabilities>
      <capability id="asynchronous" >Asynchronous</capability>
      <capability id="internal" >Internal</capability>
      <capability id="write-back" >Write-back</capability>
     </capabilities>
    </node>
    <node id="cpu:3" claimed="true" class="processor" handle="DMI:000F">
     <description>CPU</description>
     <vendor>Intel(R) Corporation</vendor>
     <physid>f</physid>
     <businfo>cpu@3</businfo>
     <version>Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz</version>
     <slot>U2E1</slot>
     <size units="Hz">800000000</size>
     <capacity units="Hz">800000000</capacity>
     <clock units="Hz">25000000</clock>
     <capabilities>
      <capability id="cpufreq" >CPU Frequency scaling</capability>
     </capabilities>
      <node id="cache:0" claimed="true" class="memory" handle="DMI:0011">
       <description>L1 cache</description>
       <physid>11</physid>
       <slot>Unknown</slot>
       <size units="bytes">32768</size>
       <capacity units="bytes">32768</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
       </capabilities>
      </node>
      <node id="cache:1" claimed="true" class="memory" handle="DMI:0012">
       <description>L2 cache</description>
       <physid>12</physid>
       <slot>Unknown</slot>
       <size units="bytes">262144</size>
       <capacity units="bytes">262144</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
        <capability id="instruction" >Instruction cache</capability>
       </capabilities>
      </node>
      <node id="cache:2" claimed="true" class="memory" handle="DMI:0013">
       <description>L3 cache</description>
       <physid>13</physid>
       <slot>Unknown</slot>
       <size units="bytes">4096</size>
       <capacity units="bytes">4096</capacity>
       <capabilities>
        <capability id="asynchronous" >Asynchronous</capability>
        <capability id="internal" >Internal</capability>
        <capability id="write-back" >Write-back</capability>
        <capability id="instruction" >Instruction cache</capability>
       </capabilities>
      </node>
    </node>
    <node id="cache:3" claimed="true" class="memory" handle="DMI:0010">
     <description>L1 cache</description>
     <physid>10</physid>
     <slot>Unknown</slot>
     <size units="bytes">32768</size>
     <capacity units="bytes">32768</capacity>
     <capabilities>
      <capability id="asynchronous" >Asynchronous</capability>
      <capability id="internal" >Internal</capability>
      <capability id="write-back" >Write-back</capability>
     </capabilities>
    </node>
    <node id="memory" claimed="true" class="memory" handle="DMI:0014">
     <description>System Memory</description>
     <physid>14</physid>
     <slot>System board or motherboard</slot>
     <size units="bytes">8589934592</size>
      <node id="bank:0" claimed="true" class="memory" handle="DMI:0016">
       <description>SODIMM DDR3 Synchronous 1600 MHz (0,6 ns)</description>
       <product>HMT451S6MFR8A-PB</product>
       <vendor>Hynix Semiconductor (Hyundai Electronics)</vendor>
       <physid>0</physid>
       <serial>0x00000000</serial>
       <slot>DIMM0</slot>
       <size units="bytes">4294967296</size>
       <clock units="Hz">1600000000</clock>
      </node>
      <node id="bank:1" claimed="true" class="memory" handle="DMI:0018">
       <description>SODIMM DDR3 Synchronous 1600 MHz (0,6 ns)</description>
       <product>HMT451S6MFR8A-PB</product>
       <vendor>Hynix Semiconductor (Hyundai Electronics)</vendor>
       <physid>1</physid>
       <serial>0x00000000</serial>
       <slot>DIMM0</slot>
       <size units="bytes">4294967296</size>
       <clock units="Hz">1600000000</clock>
      </node>
    </node>
    <node id="firmware" claimed="true" class="memory" handle="">
     <description>BIOS</description>
     <vendor>Apple Inc.</vendor>
     <physid>1a</physid>
     <version>MBA51.88Z.00EF.B01.1207271122</version>
     <date>07/27/2012</date>
     <size units="bytes">1048576</size>
     <capacity units="bytes">8323072</capacity>
     <capabilities>
      <capability id="pci" >PCI bus</capability>
      <capability id="upgrade" >BIOS EEPROM can be upgraded</capability>
      <capability id="shadowing" >BIOS shadowing</capability>
      <capability id="cdboot" >Booting from CD-ROM/DVD</capability>
      <capability id="bootselect" >Selectable boot path</capability>
      <capability id="acpi" >ACPI</capability>
      <capability id="ieee1394boot" >Booting from IEEE1394 (Firewire)</capability>
      <capability id="smartbattery" >Smart battery</capability>
      <capability id="netboot" >Function-key initiated network service boot</capability>
     </capabilities>
    </node>
    <node id="pci" claimed="true" class="bridge" handle="PCIBUS:0000:00">
     <description>Host bridge</description>
     <product>3rd Gen Core processor DRAM Controller</product>
     <vendor>Intel Corporation</vendor>
     <physid>100</physid>
     <businfo>pci@0000:00:00.0</businfo>
     <version>09</version>
     <width units="bits">32</width>
     <clock units="Hz">33000000</clock>
      <node id="display" claimed="true" class="display" handle="PCI:0000:00:02.0">
       <description>VGA compatible controller</description>
       <product>3rd Gen Core processor Graphics Controller</product>
       <vendor>Intel Corporation</vendor>
       <physid>2</physid>
       <businfo>pci@0000:00:02.0</businfo>
       <version>09</version>
       <width units="bits">64</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="i915" />
        <setting id="latency" value="0" />
       </configuration>
       <capabilities>
        <capability id="msi" >Message Signalled Interrupts</capability>
        <capability id="pm" >Power Management</capability>
        <capability id="vga_controller" />
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
        <capability id="rom" >extension ROM</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="45" />
        <resource type="memory" value="a0000000-a03fffff" />
        <resource type="memory" value="90000000-9fffffff" />
        <resource type="ioport" value="2000(size=64)" />
       </resources>
      </node>
      <node id="usb:0" claimed="true" class="bus" handle="PCI:0000:00:14.0">
       <description>USB controller</description>
       <product>7 Series/C210 Series Chipset Family USB xHCI Host Controller</product>
       <vendor>Intel Corporation</vendor>
       <physid>14</physid>
       <businfo>pci@0000:00:14.0</businfo>
       <version>04</version>
       <width units="bits">64</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="xhci_hcd" />
        <setting id="latency" value="0" />
       </configuration>
       <capabilities>
        <capability id="pm" >Power Management</capability>
        <capability id="msi" >Message Signalled Interrupts</capability>
        <capability id="xhci" />
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="43" />
        <resource type="memory" value="a0600000-a060ffff" />
       </resources>
      </node>
      <node id="communication" claimed="true" class="communication" handle="PCI:0000:00:16.0">
       <description>Communication controller</description>
       <product>7 Series/C210 Series Chipset Family MEI Controller #1</product>
       <vendor>Intel Corporation</vendor>
       <physid>16</physid>
       <businfo>pci@0000:00:16.0</businfo>
       <version>04</version>
       <width units="bits">64</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="mei" />
        <setting id="latency" value="0" />
       </configuration>
       <capabilities>
        <capability id="pm" >Power Management</capability>
        <capability id="msi" >Message Signalled Interrupts</capability>
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="46" />
        <resource type="memory" value="a0617100-a061710f" />
       </resources>
      </node>
      <node id="usb:1" claimed="true" class="bus" handle="PCI:0000:00:1a.0">
       <description>USB controller</description>
       <product>7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2</product>
       <vendor>Intel Corporation</vendor>
       <physid>1a</physid>
       <businfo>pci@0000:00:1a.0</businfo>
       <version>04</version>
       <width units="bits">32</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="ehci-pci" />
        <setting id="latency" value="0" />
       </configuration>
       <capabilities>
        <capability id="pm" >Power Management</capability>
        <capability id="debug" >Debug port</capability>
        <capability id="ehci" >Enhanced Host Controller Interface (USB2)</capability>
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="23" />
        <resource type="memory" value="a0616c00-a0616fff" />
       </resources>
      </node>
      <node id="multimedia" claimed="true" class="multimedia" handle="PCI:0000:00:1b.0">
       <description>Audio device</description>
       <product>7 Series/C210 Series Chipset Family High Definition Audio Controller</product>
       <vendor>Intel Corporation</vendor>
       <physid>1b</physid>
       <businfo>pci@0000:00:1b.0</businfo>
       <version>04</version>
       <width units="bits">64</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="snd_hda_intel" />
        <setting id="latency" value="0" />
       </configuration>
       <capabilities>
        <capability id="pm" >Power Management</capability>
        <capability id="msi" >Message Signalled Interrupts</capability>
        <capability id="pciexpress" >PCI Express</capability>
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="47" />
        <resource type="memory" value="a0610000-a0613fff" />
       </resources>
      </node>
      <node id="pci:0" claimed="true" class="bridge" handle="PCIBUS:0000:01">
       <description>PCI bridge</description>
       <product>7 Series/C210 Series Chipset Family PCI Express Root Port 1</product>
       <vendor>Intel Corporation</vendor>
       <physid>1c</physid>
       <businfo>pci@0000:00:1c.0</businfo>
       <version>c4</version>
       <width units="bits">32</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="pcieport" />
       </configuration>
       <capabilities>
        <capability id="pci" />
        <capability id="pciexpress" >PCI Express</capability>
        <capability id="msi" >Message Signalled Interrupts</capability>
        <capability id="pm" >Power Management</capability>
        <capability id="normal_decode" />
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="40" />
        <resource type="memory" value="a0500000-a05fffff" />
       </resources>
      </node>
      <node id="pci:1" claimed="true" class="bridge" handle="PCIBUS:0000:02">
       <description>PCI bridge</description>
       <product>7 Series/C210 Series Chipset Family PCI Express Root Port 2</product>
       <vendor>Intel Corporation</vendor>
       <physid>1c.1</physid>
       <businfo>pci@0000:00:1c.1</businfo>
       <version>c4</version>
       <width units="bits">32</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="pcieport" />
       </configuration>
       <capabilities>
        <capability id="pci" />
        <capability id="pciexpress" >PCI Express</capability>
        <capability id="msi" >Message Signalled Interrupts</capability>
        <capability id="pm" >Power Management</capability>
        <capability id="normal_decode" />
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="41" />
        <resource type="memory" value="a0400000-a04fffff" />
       </resources>
        <node id="network" claimed="true" class="network" handle="PCI:0000:02:00.0">
         <description>Network controller</description>
         <product>BCM43224 802.11a/b/g/n</product>
         <vendor>Broadcom Corporation</vendor>
         <physid>0</physid>
         <businfo>pci@0000:02:00.0</businfo>
         <version>01</version>
         <width units="bits">64</width>
         <clock units="Hz">33000000</clock>
         <configuration>
          <setting id="driver" value="bcma-pci-bridge" />
          <setting id="latency" value="0" />
         </configuration>
         <capabilities>
          <capability id="pm" >Power Management</capability>
          <capability id="msi" >Message Signalled Interrupts</capability>
          <capability id="pciexpress" >PCI Express</capability>
          <capability id="bus_master" >bus mastering</capability>
          <capability id="cap_list" >PCI capabilities listing</capability>
         </capabilities>
         <resources>
          <resource type="irq" value="17" />
          <resource type="memory" value="a0400000-a0403fff" />
         </resources>
        </node>
      </node>
      <node id="pci:2" claimed="true" class="bridge" handle="PCIBUS:0000:03">
       <description>PCI bridge</description>
       <product>7 Series/C210 Series Chipset Family PCI Express Root Port 5</product>
       <vendor>Intel Corporation</vendor>
       <physid>1c.4</physid>
       <businfo>pci@0000:00:1c.4</businfo>
       <version>c4</version>
       <width units="bits">32</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="pcieport" />
       </configuration>
       <capabilities>
        <capability id="pci" />
        <capability id="pciexpress" >PCI Express</capability>
        <capability id="msi" >Message Signalled Interrupts</capability>
        <capability id="pm" >Power Management</capability>
        <capability id="normal_decode" />
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="42" />
        <resource type="ioport" value="3000(size=12288)" />
        <resource type="memory" value="a0700000-ac9fffff" />
        <resource type="ioport" value="aca00000(size=201326592)" />
       </resources>
      </node>
      <node id="usb:2" claimed="true" class="bus" handle="PCI:0000:00:1d.0">
       <description>USB controller</description>
       <product>7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1</product>
       <vendor>Intel Corporation</vendor>
       <physid>1d</physid>
       <businfo>pci@0000:00:1d.0</businfo>
       <version>04</version>
       <width units="bits">32</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="ehci-pci" />
        <setting id="latency" value="0" />
       </configuration>
       <capabilities>
        <capability id="pm" >Power Management</capability>
        <capability id="debug" >Debug port</capability>
        <capability id="ehci" >Enhanced Host Controller Interface (USB2)</capability>
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="22" />
        <resource type="memory" value="a0616800-a0616bff" />
       </resources>
      </node>
      <node id="isa" claimed="true" class="bridge" handle="PCI:0000:00:1f.0">
       <description>ISA bridge</description>
       <product>QS77 Express Chipset LPC Controller</product>
       <vendor>Intel Corporation</vendor>
       <physid>1f</physid>
       <businfo>pci@0000:00:1f.0</businfo>
       <version>04</version>
       <width units="bits">32</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="driver" value="lpc_ich" />
        <setting id="latency" value="0" />
       </configuration>
       <capabilities>
        <capability id="isa" />
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="0" />
       </resources>
      </node>
      <node id="storage" claimed="true" class="storage" handle="PCI:0000:00:1f.2">
       <description>SATA controller</description>
       <product>7 Series Chipset Family 6-port SATA Controller [AHCI mode]</product>
       <vendor>Intel Corporation</vendor>
       <physid>1f.2</physid>
       <businfo>pci@0000:00:1f.2</businfo>
       <version>04</version>
       <width units="bits">32</width>
       <clock units="Hz">66000000</clock>
       <configuration>
        <setting id="driver" value="ahci" />
        <setting id="latency" value="0" />
       </configuration>
       <capabilities>
        <capability id="storage" />
        <capability id="msi" >Message Signalled Interrupts</capability>
        <capability id="pm" >Power Management</capability>
        <capability id="ahci_1.0" />
        <capability id="bus_master" >bus mastering</capability>
        <capability id="cap_list" >PCI capabilities listing</capability>
       </capabilities>
       <resources>
        <resource type="irq" value="44" />
        <resource type="ioport" value="2098(size=8)" />
        <resource type="ioport" value="20bc(size=4)" />
        <resource type="ioport" value="2090(size=8)" />
        <resource type="ioport" value="20b8(size=4)" />
        <resource type="ioport" value="2060(size=32)" />
        <resource type="memory" value="a0616000-a06167ff" />
       </resources>
      </node>
      <node id="serial" class="bus" handle="PCI:0000:00:1f.3">
       <description>SMBus</description>
       <product>7 Series/C210 Series Chipset Family SMBus Controller</product>
       <vendor>Intel Corporation</vendor>
       <physid>1f.3</physid>
       <businfo>pci@0000:00:1f.3</businfo>
       <version>04</version>
       <width units="bits">64</width>
       <clock units="Hz">33000000</clock>
       <configuration>
        <setting id="latency" value="0" />
       </configuration>
       <resources>
        <resource type="memory" value="a0617000-a06170ff" />
        <resource type="ioport" value="efa0(size=32)" />
       </resources>
      </node>
    </node>
    <node id="scsi:0" claimed="true" class="storage" handle="">
     <physid>2</physid>
     <logicalname>scsi0</logicalname>
     <capabilities>
      <capability id="emulated" >Emulated device</capability>
     </capabilities>
      <node id="disk" claimed="true" class="disk" handle="SCSI:00:00:00:00">
       <description>ATA Disk</description>
       <product>APPLE SSD SM512E</product>
       <physid>0.0.0</physid>
       <businfo>scsi@0:0.0.0</businfo>
       <logicalname>/dev/sda</logicalname>
       <dev>8:0</dev>
       <version>CXM0</version>
       <serial>S0YENYAC762532</serial>
       <size units="bytes">500277790720</size>
       <configuration>
        <setting id="ansiversion" value="5" />
        <setting id="sectorsize" value="4096" />
       </configuration>
       <capabilities>
        <capability id="partitioned" >Partitioned disk</capability>
        <capability id="partitioned:dos" >MS-DOS partition table</capability>
       </capabilities>
        <node id="volume:0" class="volume" handle="">
         <description>EFI GPT partition</description>
         <physid>1</physid>
         <businfo>scsi@0:0.0.0,1</businfo>
         <capacity>209735168</capacity>
         <capabilities>
          <capability id="primary" >Primary partition</capability>
          <capability id="nofs" >No filesystem</capability>
         </capabilities>
        </node>
        <node id="volume:1" claimed="true" class="volume" handle="">
         <description>Darwin/OS X HFS+ partition</description>
         <vendor>Mac OS X (journaled)</vendor>
         <physid>2</physid>
         <businfo>scsi@0:0.0.0,2</businfo>
         <logicalname>/dev/sda2</logicalname>
         <dev>8:2</dev>
         <version>4</version>
         <serial>47234807-a2e0-ba3c-0000-000000e89000</serial>
         <size units="bytes">33683525632</size>
         <capacity>33683525632</capacity>
         <configuration>
          <setting id="boot" value="osx" />
          <setting id="checked" value="2012-10-19 04:57:54" />
          <setting id="created" value="2012-10-19 01:57:54" />
          <setting id="filesystem" value="hfsplus" />
          <setting id="lastmountedby" value="HFSJ" />
          <setting id="modified" value="2013-06-11 12:14:38" />
          <setting id="state" value="clean" />
         </configuration>
         <capabilities>
          <capability id="primary" >Primary partition</capability>
          <capability id="bootable" >Bootable partition (active)</capability>
          <capability id="journaled" />
          <capability id="osx" >Contains a bootable Mac OS X installation</capability>
          <capability id="hfsplus" >MacOS HFS+</capability>
          <capability id="initialized" >initialized volume</capability>
         </capabilities>
        </node>
        <node id="volume:2" claimed="true" class="volume" handle="">
         <description>Darwin/OS X HFS+ partition</description>
         <vendor>Mac OS X (journaled)</vendor>
         <physid>3</physid>
         <businfo>scsi@0:0.0.0,3</businfo>
         <logicalname>/dev/sda3</logicalname>
         <dev>8:3</dev>
         <version>4</version>
         <serial>55724187-98b3-725b-0000-000000005000</serial>
         <size units="bytes">650002432</size>
         <capacity>650002432</capacity>
         <configuration>
          <setting id="boot" value="osx" />
          <setting id="checked" value="2012-10-19 04:59:42" />
          <setting id="created" value="2012-10-19 01:59:42" />
          <setting id="filesystem" value="hfsplus" />
          <setting id="lastmountedby" value="HFSJ" />
          <setting id="modified" value="2012-10-19 05:37:56" />
          <setting id="state" value="clean" />
         </configuration>
         <capabilities>
          <capability id="primary" >Primary partition</capability>
          <capability id="journaled" />
          <capability id="bootable" />
          <capability id="macos" >Contains a bootable Mac OS installation</capability>
          <capability id="osx" >Contains a bootable Mac OS X installation</capability>
          <capability id="hfsplus" >MacOS HFS+</capability>
          <capability id="initialized" >initialized volume</capability>
         </capabilities>
        </node>
        <node id="volume:3" claimed="true" class="volume" handle="">
         <description>Linux filesystem partition</description>
         <physid>4</physid>
         <businfo>scsi@0:0.0.0,4</businfo>
         <logicalname>/dev/sda4</logicalname>
         <dev>8:4</dev>
         <capacity>1048576</capacity>
         <capabilities>
          <capability id="primary" >Primary partition</capability>
         </capabilities>
        </node>
      </node>
    </node>
    <node id="scsi:1" claimed="true" class="storage" handle="SCSI:06">
     <physid>3</physid>
     <businfo>usb@2:1.8.3</businfo>
     <logicalname>scsi6</logicalname>
     <configuration>
      <setting id="driver" value="usb-storage" />
     </configuration>
     <capabilities>
      <capability id="emulated" >Emulated device</capability>
      <capability id="scsi-host" >SCSI host adapter</capability>
     </capabilities>
      <node id="disk" claimed="true" class="disk" handle="SCSI:06:00:00:00">
       <description>SCSI Disk</description>
       <product>SD Card Reader</product>
       <vendor>APPLE</vendor>
       <physid>0.0.0</physid>
       <businfo>scsi@6:0.0.0</businfo>
       <logicalname>/dev/sdb</logicalname>
       <dev>8:16</dev>
       <version>2.00</version>
       <configuration>
        <setting id="sectorsize" value="512" />
       </configuration>
       <capabilities>
        <capability id="removable" >support is removable</capability>
       </capabilities>
        <node id="medium" claimed="true" class="disk" handle="">
         <physid>0</physid>
         <logicalname>/dev/sdb</logicalname>
         <dev>8:16</dev>
        </node>
      </node>
    </node>
    <node id="scsi:2" claimed="true" class="storage" handle="SCSI:22">
     <physid>4</physid>
     <businfo>usb@3:1</businfo>
     <logicalname>scsi22</logicalname>
     <configuration>
      <setting id="driver" value="usb-storage" />
     </configuration>
     <capabilities>
      <capability id="emulated" >Emulated device</capability>
      <capability id="scsi-host" >SCSI host adapter</capability>
     </capabilities>
      <node id="disk:0" claimed="true" class="disk" handle="SCSI:22:00:00:00">
       <description>SCSI Disk</description>
       <physid>0.0.0</physid>
       <businfo>scsi@22:0.0.0</businfo>
       <logicalname>/dev/sdc</logicalname>
       <dev>8:32</dev>
       <configuration>
        <setting id="sectorsize" value="512" />
       </configuration>
      </node>
      <node id="disk:1" claimed="true" class="disk" handle="SCSI:22:00:00:01">
       <description>SCSI Disk</description>
       <physid>0.0.1</physid>
       <businfo>scsi@22:0.0.1</businfo>
       <logicalname>/dev/sdd</logicalname>
       <dev>8:48</dev>
       <configuration>
        <setting id="sectorsize" value="512" />
       </configuration>
      </node>
    </node>
  </node>
  <node id="battery" claimed="true" class="power" handle="DMI:0031">
   <product>Unknown</product>
   <vendor>Unknown</vendor>
   <physid>1</physid>
   <version>Unknown</version>
   <serial>Unknown</serial>
   <slot>Unknown</slot>
  </node>
  <node id="network:0" claimed="true" class="network" handle="">
   <description>Ethernet interface</description>
   <physid>2</physid>
   <logicalname>vnet0</logicalname>
   <serial>fe:54:00:c1:1a:f7</serial>
   <size units="bit/s">10000000</size>
   <configuration>
    <setting id="autonegotiation" value="off" />
    <setting id="broadcast" value="yes" />
    <setting id="driver" value="tun" />
    <setting id="driverversion" value="1.6" />
    <setting id="duplex" value="full" />
    <setting id="link" value="yes" />
    <setting id="multicast" value="yes" />
    <setting id="port" value="twisted pair" />
    <setting id="speed" value="10Mbit/s" />
   </configuration>
   <capabilities>
    <capability id="ethernet" />
    <capability id="physical" >Physical interface</capability>
   </capabilities>
  </node>
  <node id="network:1" claimed="true" class="network" handle="">
   <description>Ethernet interface</description>
   <physid>3</physid>
   <logicalname>tap0</logicalname>
   <serial>e2:66:69:22:be:fb</serial>
   <size units="bit/s">10000000</size>
   <configuration>
    <setting id="autonegotiation" value="off" />
    <setting id="broadcast" value="yes" />
    <setting id="driver" value="tun" />
    <setting id="driverversion" value="1.6" />
    <setting id="duplex" value="full" />
    <setting id="ip" value="10.152.18.103" />
    <setting id="link" value="yes" />
    <setting id="multicast" value="yes" />
    <setting id="port" value="twisted pair" />
    <setting id="speed" value="10Mbit/s" />
   </configuration>
   <capabilities>
    <capability id="ethernet" />
    <capability id="physical" >Physical interface</capability>
   </capabilities>
  </node>
  <node id="network:2" claimed="true" class="network" handle="">
   <description>Wireless interface</description>
   <physid>4</physid>
   <logicalname>wlan0</logicalname>
   <serial>00:88:65:35:2b:50</serial>
   <configuration>
    <setting id="broadcast" value="yes" />
    <setting id="driver" value="brcmsmac" />
    <setting id="driverversion" value="3.8.0-26-generic" />
    <setting id="firmware" value="N/A" />
    <setting id="ip" value="192.168.12.13" />
    <setting id="link" value="yes" />
    <setting id="multicast" value="yes" />
    <setting id="wireless" value="IEEE 802.11abgn" />
   </configuration>
   <capabilities>
    <capability id="ethernet" />
    <capability id="physical" >Physical interface</capability>
    <capability id="wireless" >Wireless-LAN</capability>
   </capabilities>
  </node>
</node>
</list>
'''
